table: directus_settings

fields:
  - field: id
    hidden: true

  - field: project_name
    interface: input
    options:
      iconRight: title
      placeholder: My project...
    translations:
      language: en-US
      translations: Name
    width: half

  - field: project_url
    interface: input
    options:
      iconRight: link
      placeholder: https://example.com
    translations:
      language: en-US
      translations: Website
    width: half

  - field: project_color
    interface: select-color
    note: Login & Logo Background
    translations:
      language: en-US
      translations: Brand Color
    width: half

  - field: project_logo
    interface: file
    note: White 40x40 SVG/PNG
    translations:
      language: en-US
      translations: Brand Logo
    width: half

  - field: public_divider
    interface: presentation-divider
    options:
      icon: public
      title: Public Pages
    special:
      - alias
      - no-data
    width: full

  - field: public_foreground
    interface: file
    translations:
      language: en-US
      translations: Login Foreground
    width: half

  - field: public_background
    interface: file
    translations:
      language: en-US
      translations: Login Background
    width: half

  - field: public_note
    interface: input-multiline
    options:
      placeholder: A short, public message that supports markdown formatting...
    width: full

  - field: security_divider
    interface: presentation-divider
    options:
      icon: security
      title: Security
    special:
      - alias
      - no-data
    width: full

  - field: auth_password_policy
    interface: select-dropdown
    options:
      choices:
        - value: null
          text: None – Not Recommended
        - value: '/^.{8,}$/'
          text: Weak – Minimum 8 Characters
        - value: "/(?=^.{8,}$)(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+}{';'?>.<,])(?!.*\\s).*$/"
          text: Strong – Upper / Lowercase / Numbers / Special
      allowOther: true
    width: half

  - field: auth_login_attempts
    interface: input
    options:
      iconRight: lock
      placeholder: $t:unlimited
    width: half

  - field: files_divider
    interface: presentation-divider
    options:
      icon: storage
      title: Files & Thumbnails
    special:
      - alias
      - no-data
    width: full

  - field: storage_asset_presets
    interface: list
    options:
      fields:
        - field: key
          name: Key
          type: string
          schema:
            is_nullable: false
          meta:
            interface: input
            options:
              slug: true
              onlyOnCreate: false
            width: full
        - field: fit
          name: Fit
          type: string
          schema:
            is_nullable: false
          meta:
            interface: select-dropdown
            options:
              choices:
                - value: contain
                  text: Contain (preserve aspect ratio)
                - value: cover
                  text: Cover (forces exact size)
                - value: inside
                  text: Fit inside
                - value: outside
                  text: Fit outside
            width: half
        - field: width
          name: Width
          type: integer
          schema:
            is_nullable: false
          meta:
            interface: input
            width: half
        - field: height
          name: Height
          type: integer
          schema:
            is_nullable: false
          meta:
            interface: input
            width: half
        - field: quality
          type: integer
          name: Quality
          schema:
            default_value: 80
            is_nullable: false
          meta:
            interface: slider
            options:
              max: 100
              min: 0
              step: 1
            width: half
        - field: withoutEnlargement
          name: Upscaling
          type: boolean
          schema:
            default_value: false
          meta:
            interface: boolean
            width: half
            options:
              label: Don't upscale images
        - field: format
          name: Format
          type: string
          schema:
            is_nullable: false
            default_value: ''
          meta:
            interface: select-dropdown
            options:
              allowNone: true
              choices:
                - value: jpeg
                  text: JPEG
                - value: png
                  text: PNG
                - value: webp
                  text: WebP
                - value: tiff
                  text: Tiff
            width: half
        - field: transforms
          name: Additional Transformations
          type: json
          schema:
            is_nullable: false
            default_value: []
          meta:
            note:
              The Sharp method name and its arguments. See https://sharp.pixelplumbing.com/api-constructor for more
              information.
            interface: json
            options:
              template: >
                [
                  ["blur", 45],
                  ["grayscale"],
                  ["extend", { "right": 500, "background": "rgb(255, 0, 0)" }]
                ]
              placeholder: >
                [
                  ["blur", 45],
                  ["grayscale"],
                  ["extend", { "right": 500, "background": "rgb(255, 0, 0)" }]
                ]
            width: full
      template: '{{key}}'
    special: json
    width: full

  - field: storage_asset_transform
    interface: select-dropdown
    options:
      choices:
        - value: all
          text: All
        - value: none
          text: None
        - value: presets
          text: Presets Only
    width: half

  - field: storage_default_folder
    interface: system-folder
    width: half
    note: Default folder where new files are uploaded

  - field: overrides_divider
    interface: presentation-divider
    options:
      icon: brush
      title: App Overrides
    special:
      - alias
      - no-data
    width: full

  - field: custom_css
    interface: input-code
    options:
      language: css
      lineNumber: true
    width: full
