name: E2E
on:
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        db: ['postgres']
        node-version: ['16-alpine']
    env:
      CACHED_IMAGE: ghcr.io/directus/directus-e2e-test-cache:${{ matrix.node-version }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: restore node_modules cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Run tests
        env:
          TEST_NODE_VERSION: ${{ matrix.node-version }}
          TEST_DB: ${{ matrix.db }}
        run: npm run test:e2e
